_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 3
                - 30
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 3
                - 30
                - 41
                - 49
                - 51
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.11.9
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
